### ISSUE TITLE
RequestParameters.ConnectionTimeout is mistakenly internal

### ISSUE THREAD

**Issue by mazharenko** [vostok/clusterclient.core#14]
An `IRequestStrategy` implementation is responsible for sending a request to the whole cluster via `IRequestSender`, defining when and in which order the replicas must be sent the request to.

`IRequestSender`, for its part, needs a set of parameters, among which is `connectionTimeout`. Unfortunately, `RequestParameters`, which contains its value, defines the corresponding property as `internal`, which impedes the correct implementation of `IRequestStrategy` outside of the clusterclient.core assembly.

If extensibility is the priority, I suggest the property should have been defined as public. On the other hand, there might have been weighty reasons for the property to be internal, therefore, I cannot assess the implications of such a solution.

**Comment by iloktionov** [comment]
Connection timeout was initially made internal in order to prevent usage of unique connection timeouts for each request. Our reason for this is that `SocketsTransport`, default transport implementation for .NET Core, would leak memory if presented with a lot of different connection timeout values. It's based on `SocketsHttpHandler` which, unfortunately, does not support passing connection timeout on a per-request basis and instead makes it a property of its entire internal connection pool. So we have to cache these handlers with connection timeout being a part of the cache key. A lot of unique timeouts = resource leak.

That being said, there's absolutely no reason to prevent custom strategies from _reading_ the value. I will fix that.
