### ISSUE TITLE
Stale list of replicas in IRequestStrategy while executing strategy with huge timeouts.

### ISSUE THREAD

**Issue by deniaa** [vostok/clusterclient.core#8]
Look at this example.

We want to send request with strategy. Forking strategy, for example.

At this line we already have fixed list of replicas. With predefined order. (https://github.com/vostok/clusterclient.core/blob/master/Vostok.ClusterClient.Core/Modules/RequestExecutionModule.cs#L55)

My request have 1 minutes timeout and strategy have 20 seconds foking delay.
15 seconds after the start of the request all my replicas fell and went up on another host:ports.
All requests that my strategy sends to other replicas (which are stale already) will guarantee failure.

May be pass real topology provider into strategy execution will be not too hard. Even with remembering already used replicas and considering weights.

**Comment by iloktionov** [comment]
That would be exceptionally hard to implement as described in the issue due to internal architecture of the library. However, there's one possible workaround involving retry mechanics and [AdHocRetryPolicy](https://github.com/vostok/clusterclient.core/blob/master/Vostok.ClusterClient.Core/Retry/AdHocRetryPolicy.cs). One could just retry when following conditions hold during retry policy evaluation:
1. Request has failed, using all of its replica limit (3 by default).
2. None of the used replicas are among the current ones (as returned by the cluster provider).

**Comment by iloktionov** [comment]
Closing this as there's a reasonable workaround and no plans to fix this whatsoever.
